<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/

$config['base_url'] = 'https://jukebox5d.com/app/';


/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = 'jukebox5d';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| This is particularly useful for portability between UNIX-based OSes,
| (usually \n) and Windows (\r\n).
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';



/*
|--------------------------------------------------------------------------
| My Config Sosmed connect
|--------------------------------------------------------------------------
*/
$config["path_client_id"] = "b2b94451e0b79e1a4a730f0c3dc70dc2ba84d155"; // sticko456@yahoo.com
$config["path_client_secret"] = "de13470eed7df31ed83e0a9d1e3ea0768e8a0f0f"; // sticko456@yahoo.com
$config["google_developer_key"] = "AIzaSyAQUfn5rNFVjfW1uFURvOENHqfycm8NY_Q"; // arwin@limadigit.com
$config["soundcloud_id"] = "484e4f6b160e6f2cc9f68167656afc2c"; // sticko456@gmail.com
$config["soundcloud_key"] = "5019216ddfb09d516d371464f8ccf3b8"; // sticko456@gmail.com
$config["recaptcha_secret"] = "6Lc_qQkUAAAAAPtP4JkpyYj7AtCz_htytYmVrCY8"; // arwin@limadigit.com

/*
|--------------------------------------------------------------------------
| My Config Profile
|--------------------------------------------------------------------------
*/
$config["genre"] = array("Blues","Rock","Country","Dance/Electronic","Funk","Hip-Hop/Rap","Jazz","Metal","Pop","R&B/Soul","Reggae","Classical","Instrumental","Dangdut","K-Pop","J-Pop","Cantopop","Mandopop","Folk","Indie");
$config["music_genre_title"] = "Music Genre";
$config["food_title"] = "Favorite Food";
$config["drink_title"] = "Favorite Drink";
$config["hangout_place_title"] = "Favorite Hangout Place";
$config["about_title"] = "About";

/*
|--------------------------------------------------------------------------
| My Config Email
|--------------------------------------------------------------------------
*/
$config['subjectResetPass'] = 'Reset your password';
$config['contentResetPass'] = 'Hi [user]! <br/><br/>

Kami menerima permintaan Anda untuk mengatur ulang (reset) password akun Anda. <br/>
Jika Anda meminta pengaturan ulang (reset), silakan klik link di bawah ini. Jika Anda tidak membuat permintaan ini, abaikan email ini. <br/><br/>

https://jukebox5d.com/app/index.php/newPassword?code=[code] <br/><br/>

Anda dapat mengubah pengaturan profil Anda membutuhkan informasi pribadi untuk mereset password Anda. <br/><br/>

Terima kasih,<br/><br/>

Tim Jukebox 5D<br/> 
limadigit.com';

$config['subjectEmailConfirmation'] = "Email Confirmation for Jukebox 5D";
$config['contentEmailConfirmation'] = "Halo Jukebox-ers!<br/><br/>
								
								Terima kasih telah melakukan registrasi Jukebox 5D.<br/>
								Kamu kini menjadi bagian dari salah satu komunitas musik di Indonesia, Jukebox 5D.<br/>
								Melalui email ini, Kamu telah resmi terdaftar sebagai [user] Jukebox 5D.<br/><br/>								
								
								Langkah selanjutnya, silahkan klik tombol konfirmasi berikut:<br/>
								http://jukebox5d.com/app/index.php/register/confirmation?u=[uniqueid]<br/><br/>
								
								Untuk informasi lebih lanjut mengenai cara penggunaan Jukebox 5D,<br/>
								klik: http://bit.ly/2cBkPPh atau klik: limadigit.com/jukebox5d<br/><br/>
								
								Untuk mengetahui update informasi musik dan Jukebox 5D terkini, serta berpartisipasi langsung di komunitas ini,<br/>
								like Facebook Jukebox 5D dengan mengeklik: https://www.facebook.com/Jukebox5D<br/>
								follow Twitter @jukebox5d dan<br/>
								follow Instagram @jukebox5d	<br/><br/>
								
								Ayo ajak teman-teman Kamu lainnya menjadi bagian dari komunitas keren ini!<br/>
								Suara Kamu sangat berharga untuk kemajuan musik di Indonesia.<br/><br/>
								
								Terima kasih,<br/><br/>

								Tim Jukebox 5D<br/> 
								limadigit.com";
								
$config['subjectNotifMe'] = "Jukebox 5D new registration";
$config['contentNotifMe'] = "new user <b>[username]</b> register sebagai <b>[status]</b>";
$config['from_email']="explore@limadigi.com";
$config['from_email_name']="Jukebox 5D";

/*
|--------------------------------------------------------------------------
| My Config Content HTML User
|--------------------------------------------------------------------------
*/
$config['title']="JUKEBOX 5D";
$config['delimiter'] = "•♪•";
$config['subtitle'] = '"Music it\'s you. It\'s FREE!" - Jukebox 5D';
$config['copyright']="Copyright &copy; ".date("Y")." by";
$config['copyright_year']=date("Y");
$config['edit_profile']="Edit Profile";
$config['wt']="Weekly Charts";
$config['rs']="Recent Songs";
$config['ou']="Online Users";
$config['mp']="Music Playlist";
$config['cl']="Chat Lounge";
$config['mr']="Top User";
$config['ht']="How To";
$config['pp']="Privacy Policy";
$config['username']="Username";
$config['password']="Password";
$config['re-pass']="Re-type Password";
$config['register']="Register";
$config['email']="Email";
$config['forgot_pass']="Forgot Password?";
$config['sign_up']="Sign up";
$config['sign_in']="Sign in";
$config['sign_out']="Sign out";
$config['get_location']="Getting your location, please wait";
$config['5D']="Limadigit";
$config['facebook_login']="Sign in with Facebook";
$config['path_login']="Sign in with Path";
$config['choose_admin']="Choose your Admin";
$config['cancel_play']="Cancel to play?";
$config['special_day']="Hey! Please insert song from my playlist.";
$config['body_special_day']="<p>Type \"<b>all</b>\" to see the tracks.</p>";
$config['source']="Source:";
$config['empty_playlist']="DONT YOU FEEL BORED WITHOUT MUSIC?<br/>PLAY ME!";
$config['king_queen']="BE JUKEBOX 5D KING / QUEEN";
$config['most_played_title']="Insert Your Song Here and Become No 1";
$config['recent_song_title']="There's no recent song";
$config['empty_username']="username is empty";
$config['empty_message']="message cannot be empty";
$config['delete_song']="Delete Your Song?";
$config['add_song']="Add this song to your playlist?";
$config['max_caption_text']="You exceed the maximum of 50 characters for the caption, please reduce, thanks.";
$config['empty_caption']="Leave it blank if you feel nothing.";
$config['success_insert_song_title']="We love it!";
$config['success_insert_song_body']="Wait until it is played.";
$config['already_insert_title']="It\'s not your turn yet.";
$config['already_insert_body']="<p>Invite your friend to insert a song first</p>";
$config['max_two_song_per_user']="Please wait till your songs played";
$config['wait_until_success_loaded']="Please wait, until it is successfuly loaded";
$config['weekly_chart_tooltip']="Community weekly chart, be champion!";
$config['share_tooltip']="Share to your love ones";
$config['skip_tooltip']=" Skip for next song";
$config['love_tooltip']="5 love to play again <br/> Add 1 love to add 1 skip";
$config['recent_song']="See your earlier mood here";
$config['most_request_tooltip']="These are the order of the king or queen in your community";
$config['close']="Close";
$config['how_to']="How To";
$config['address']="Address";
$config['caption_title']="Tell us how you feel about this song!";
$config['caption_example']="ex: This song reminds me of my ex :(";
$config['registered_title']="Congratulation!";
$config['registered_body']="You have been registered, check your inbox email or spam for verification";
$config['registered_as']="Registered As";
$config['admin']="Admin";
$config['user']="User";
$config['choose_admin_register']="If you choose as an Admin, it means you will serve as a hub (receiver and transmitter) for all the songs played or requested by the User. You will be subject to the terms and conditions applicable to the use of Jukebox 5D.";
$config['choose_user_register']="If you choose as an user, means you can find and select your favorite songs in the search box that you will find it in the jukebox 5d application.";
$config['add_location']="To add your location in jukebox5d you must click on the map below :";
$config['add_location_notif']="If your location not accurate, please allow your GPS or location in your device.";
$config['upload_failed']="Upload failed! please try again";
$config['privacy_policy']="PRIVACY AND POLICY";
$config['privacy_policy_body']="<h4><b>WHAT INFORMATION DO WE COLLECT?</b></h4>
								
									<p>We collect information from you when you register on our site or fill out a form.
									When ordering or registering on our site or app, as appropriate, you may be asked to enter your name or e-mail address. You may, however, visit our site anonymously.
									</p>
								<br>
								<h4><b>WHAT DO WE USE YOUR INFORMATION FOR?</b></h4>
								
									<ul style=\"padding-left:20px\">
									
										<li>Any of the information we collect from you may be used in one of the following ways.</li>
										<li>To personalize your experience (your information helps us to better respond to your individual needs).</li>
										<li>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you).</li>
										<li>To Improve customer service (your information helps us to more effectively respond to your customer service requests and support needs).</li>
										<li>To process transactions.</li>
										<li>Your information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent, other than for the express purpose of delivering the purchased product or service requested by the customer.</li>
										<li>To send periodic emails.</li>
										<li>To administer a contest, promotion, survey or other site feature.</li>
									
									</ul>
									
									<p>The email address you provide for order processing, may be used to send you information and updates pertaining to your order, in addition to receiving occasional company news, updates, related product or service information, etc.
									Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions a the bottom of each email.</p>
								
								<br>
								<h4><b>HOW DO WE PROTECT YOUR INFORMATION?</b></h4>
								<p>
									We implement a variety of security measures to maintain the safety of your personal information when you access your personal information.
								</p>
								
								<br>
								<h4><b>DO WE USE COOKIES?</b></h4>
								<p>
									Yes We do use cookies.
								</p>
								
								<br>
								<h4><b>DO WE DISCLOSE ANY INFORMATION TO OUTSIDE PARTIES?</b></h4>
								<p>
									We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or prate ct ours or others rights, property, or safety. However, non- personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.
								</p>
								
								<br>
								<h4><b>THIRD PARTY LINKS</b></h4>
								<p>
									Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to prate ct the integrity of our site and welcome any feedback about these sites.
								</p>
								
								<br>
								<h4><b>ONLINE PRIVACY POLICY ONLY</b></h4>
								<p>
									This online privacy policy applies only to information collected through our website and not to information collected offline.
								</p>
								
								<br>
								<h4><b>YOUR CONSENT</b></h4>
								<p>
									By using our site, you consent to our privacy policy.
								</p>
								
								<br>
								<h4><b>CHANGES TO OUR PRIVACY POLICY</b></h4>
								<p>
									If we decide to change our privacy policy, we will post those changes on this page.
									This policy was last modified on 31 July 2015.
								</p>
								
								<br>
								<h4><b>CONTACTING US</b></h4>						
								<p>
									If there are any questions regarding this privacy policy you may contact us using the information below.
								</p>
								
								<a href=\"http://limadigit.com/\" target=\"_blank\">Limadigit</a><br>
								Komplek Kebayoran Center Blok A-17<br>
								Jl Raya Kebayoran Baru - Velbak<br>
								South Jakarta - Jakarta 12240<br>
								Indonesia<br>
								Email : explore@limadigit.com<br>
								<br>
								<br>
								<br>
								<br>
								<p>
									Jakarta, 8 Agustus 2016
								</p>
								<br>
								<br>
								<br>
								<p>
									<b>Indra Tri Pratomo</b>
									<br><b>Director</b>
								</p>";

/*
|--------------------------------------------------------------------------
| My Config Content HTML Admin
|--------------------------------------------------------------------------
*/
$config['next_song']="Next Song";
$config['empty_playlist_admin']="There\'s a hole in my soul, please fill it with your song.";
$config['waiting_playlist_admin']="Waiting for you to fill in my soul with your song";
$config['manage_playlist']="Manage Playlist";
$config['now_playing']="Now Playing";
$config['remove']="Remove";
$config['edit']="Edit";
$config['new_playlist']="Insert new playlist?";
$config['delete_song_admin']="Delete this Song?";
$config['delete_playlist_admin']="Delete this Playlist?";
$config['add_song_playlist_admin']="Are you sure you want to insert song?";
$config['community_playlist']="Community Playlist";
$config['add_playlist']="Add Playlist";
$config['playlist_name']="Playlist Name";
$config['from_date']="From";
$config['to_date']="To";
$config['submit']="Submit";

/*
|--------------------------------------------------------------------------
| My Config Content HTML Mobile
|--------------------------------------------------------------------------
*/
$config["header_android_popup"] = "Music it's you. It's free!";

/*
|--------------------------------------------------------------------------
| My Config Content Ajax
|--------------------------------------------------------------------------
*/
$config['success']="success";
$config['no_server']="There's no Jukebox 5D admin arround you";
$config['wrong_username_or_password']="Incorrect Email or Password";
$config['email_already_exist']="Email is already exist, use another.";
$config['no_email']="No Email Detected";
$config['error_update_loc']="error update location user";
$config['success_update_loc']="success update location user";
$config['skip_text']="Skip";
$config['special_day_ajax']="Please type <b>all</b> and choose your track.";
$config['error_500']="Please check your internet connection";
$config['success_change_pass']="Password Change Success";
$config['password_not_match']="Sorry your new password is not match";
$config['wrong_old_pass']="Incorrect old Password";
$config['password_regis_not_match']="Password does not match";
$config['invalid_captcha']="Invalid Captcha";
$config['no_user_found']="No User Found";

/*
|--------------------------------------------------------------------------
| My Config Default Image
|--------------------------------------------------------------------------
*/
$config['logo'] = $config['base_url'] . "assets/images/logo.png";
$config['logoAdmin'] = $config['base_url'] . "assets/images/logo-admin.svg";
$config['logo_blue'] = $config['base_url'] . "assets/images/logo_jukebox.png";
$config['logo5d2'] = $config['base_url'] . "assets/images/logo5d2.png";
$config['faveicon'] = $config['base_url'] . "assets/images/favicon.ico";
$config['logo_login_jukebox'] = $config['base_url'] . "assets/images/logo_login_jukebox.png";
$config['google_play_logo'] = $config['base_url'] . "assets/images/google-play.png";
$config['app_store_logo'] = $config['base_url'] . "assets/images/apple-logo-download.svg";
$config['path_logo'] = $config['base_url'] . "assets/images/path-logo.png";
$config['ajax_loader'] = $config['base_url'] . "assets/images/ajax-loader.gif";
$config['medal_gold'] = $config['base_url'] . "assets/images/medal-gold.png";
$config['medal_silver'] = $config['base_url'] . "assets/images/medal-silver.png";
$config['medal_bronze'] = $config['base_url'] . "assets/images/medal-bronze.png";
$config['user_default'] = $config['base_url'] . "assets/images/user.jpg";
$config['captions'] = $config['base_url'] . "assets/images/caption.png";
$config['jukebox_admin'] = $config['base_url'] . "assets/images/jukebox-admin.png";
$config['soundcloud'] = $config['base_url'] . "assets/images/soundcloud.png";
$config['youtube'] = $config['base_url'] . "assets/images/youtube2.png";
$config['equalizer'] = $config['base_url'] . "assets/images/equi-jb.gif";
$config['emoji_path'] = $config['base_url'] . "assets/emoji/lib/img/";

/*
|--------------------------------------------------------------------------
| My Config Audio Notification
|--------------------------------------------------------------------------
*/
$config['notif'] = $config['base_url'] . "assets/sound/Snare.wav";

/*
|--------------------------------------------------------------------------
| My Config Default URL
|--------------------------------------------------------------------------
*/
$config['video_tutorial'] = "https://www.youtube.com/embed/_MTlNfKSNlQ";
// $config['socketjs'] = "https://5dapps.com:8443/socket.io/socket.io.js";
$config['socketjs'] = $config["base_url"] . "assets/js/socket.io.js";
$config['port_server'] = "https://zuka.5dapps.com/";
// $config['port_server'] = "https://masmitcwp.tk/";


$config['port_server_asli'] = "https://zuka.5dapps.com/";
// $config['port_server_aslier'] = "http://35.204.196.147:8080/";

$config['soundcloud_url'] = "https://w.soundcloud.com/player/?url=";
$config['youtube_url'] = "https://www.youtube.com/iframe_api";
$config['youtube_player_url'] = "https://www.youtube.com/player_api";
$config['ig_jukebox5d'] = "https://instagram.com/jukebox5d/";
$config['twitter_jukebox5d'] = "https://twitter.com/jukebox5d/";
$config['fb_jukebox5d'] = "https://www.facebook.com/Jukebox5D/";
$config['play_store_link'] = "https://play.google.com/store/apps/details?id=com.limadigit.jukebox5dmusic&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1";
$config['app_store_link'] = "https://itunes.apple.com/id/app/jukebox-5d/id1190781622?mt=8";
$config['google_maps_script'] = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBWTLKDYhWBay7i8E9-e5bCzMEnU299Ip4&callback=initAutocomplete&libraries=places";
$config['path_oauth'] = "https://partner.path.com/oauth2/access_token";
$config['path_url_get_me'] = "https://partner.path.com/1/user/self";
$config['profile'] = "Profile";
$config['user_playlist'] = "User Playlist";
$config['http_server'] = "https://jukebox5d.com/app/index.php";
